services:
  test-db:
    image: bitnami/postgresql:latest
    ports:
      - '5433:5432'
    environment:
      - POSTGRESQL_USERNAME=${DB_USER}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_DATABASE=${DB_NAME}